revision = '5b27499b46fc'
down_revision = 'a981bc6bf411'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_account_id_fkey', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'account', ['account_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_account_id_fkey', 'post', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###
