revision = '89ac706e4899'
down_revision = 'f49b68bfa2e7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE \"account\" SET user_id = 1")
    op.execute("ALTER TABLE \"account\" ALTER COLUMN user_id SET NOT NULL")
    op.create_foreign_key(None, 'account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'user_id')
    # ### end Alembic commands ###
