revision = 'f49b68bfa2e7'
down_revision = '5b27499b46fc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('max_accounts', sa.Integer(), nullable=True))
    op.execute("UPDATE \"user\" SET max_accounts = 1000")
    op.execute("ALTER TABLE \"user\" ALTER COLUMN max_accounts SET NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'max_accounts')
    # ### end Alembic commands ###
