revision = 'a981bc6bf411'
down_revision = '7c8dfa3d56a9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_at_timezone_offset', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_at_timezone_offset')
    ### end Alembic commands ###
